version: "3.11"

services:
   app:
      build:
         context: .
         target: app

      restart: always
      env_file: .env

      environment:
         - WS_HOST=0.0.0.0

      ports:
         - "${WS_PORT}:${WS_PORT}"
